id: IB70A4B85
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T04:30:50+00:00'
last_modified: '2022-06-08T13:01:57.748301+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22118
  title: ཕར་ཕྱིན་གྱི་ཊཱིཀ་ཆེན། ༼བླ་བྲང་བཀྲ་ཤིས་འཁྱིལ་གྱི་བསྐྱར་པར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    19D5:
      image_group_id: I5629
      title: ''
      total_pages: 620
      order: 1
      base_file: 19D5.txt
    DCAB:
      image_group_id: I5630
      title: ''
      total_pages: 598
      order: 2
      base_file: DCAB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
