id: P010362
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:45:58.511388
source_metadata:
  id: bdr:W22118
  title: ཕར་ཕྱིན་གྱི་ཊཱིཀ་ཆེན། ༼བླ་བྲང་བཀྲ་ཤིས་འཁྱིལ་གྱི་བསྐྱར་པར།༽
  author: ''
  volumes:
    103ffdd7295f4dc4ae0e7171af6733c7:
      image_group_id: I5629
      title: ''
      volume_number: 1
      total_pages: 620
      base_file: v001.txt
    e226c4329bad49e08fbaa7d00d9eb0f0:
      image_group_id: I5630
      title: ''
      volume_number: 2
      total_pages: 598
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
